// MBZUAI Prep — curated practice bank.
// Scope grounded ONLY in publicly documented MBZUAI screening-exam topics
// (mbzuai.ac.ae admission pages, verified Aug 2026):
//   Math: Algebra, Functions, Probability, Statistics, Matrices & Vectors,
//         Calculus, Discrete Mathematics
//   Computational Thinking & Logic: Logic, Pattern Recognition
//   Programming Fundamentals: Algorithmic Problem Solving, Syntax Concepts,
//         Basic Data Structures
//   Data & AI Reasoning: Data Interpretation, Basic ML Concepts
// These are ORIGINAL practice questions written for MomoLearn — none are
// official or confidential MBZUAI exam questions.

export const TOPICS = [
  { id: 'algebra',    name: 'Algebra',                 group: 'Math',                     weight: 0.09 },
  { id: 'functions',  name: 'Functions',               group: 'Math',                     weight: 0.07 },
  { id: 'probability',name: 'Probability',             group: 'Math',                     weight: 0.09 },
  { id: 'statistics', name: 'Statistics',              group: 'Math',                     weight: 0.08 },
  { id: 'linear',     name: 'Matrices & Vectors',      group: 'Math',                     weight: 0.08 },
  { id: 'calculus',   name: 'Calculus',                group: 'Math',                     weight: 0.07 },
  { id: 'discrete',   name: 'Discrete Mathematics',    group: 'Math',                     weight: 0.06 },
  { id: 'logic',      name: 'Logic & Patterns',        group: 'Computational Thinking',   weight: 0.08 },
  { id: 'quant',      name: 'Quantitative Reasoning',  group: 'Computational Thinking',   weight: 0.08 },
  { id: 'programming',name: 'Programming Fundamentals',group: 'Programming',              weight: 0.10 },
  { id: 'algo',       name: 'Algorithms & Data Structures', group: 'Programming',         weight: 0.08 },
  { id: 'csf',        name: 'Computer Science Fundamentals', group: 'Programming',         weight: 0.05 },
  { id: 'dat',        name: 'Data & AI Reasoning',     group: 'Data & AI Reasoning',      weight: 0.07 },
];

export const DIFFICULTY_NAMES = { 1: 'Foundation', 2: 'Intermediate', 3: 'Advanced' };

const mcq = (id, topic, sub, diff, skill, est, q, choices, answer, exp, wrong, faster, trap, concept) =>
  ({ id, topic, sub, diff, skill, est, kind: 'mcq', q, choices, answer, exp, wrong, faster, trap, concept });
const num = (id, topic, sub, diff, skill, est, q, answer, exp, faster, trap, concept) =>
  ({ id, topic, sub, diff, skill, est, kind: 'num', q, answer, exp, faster, trap, concept });

export const QUESTIONS = [
  // ─── Algebra ──────────────────────────────────────────────
  mcq('alg1', 'algebra', 'Linear equations', 1, 'Solving one-variable linear equations', 50,
    'Solve for x: 3x − 7 = 14',
    ['x = 3', 'x = 5', 'x = 7', 'x = 9'], 2,
    'Add 7 to both sides: 3x = 21, then divide by 3: x = 7.',
    { 0: 'Subtracting 7 again instead of adding it gives x = 3.', 1: 'Dividing 14 − 7 = 7 by 3 instead of 3x = 21 gives this wrong value.' },
    'Add 7 first, then divide once — two moves total.',
    'Forgetting to apply the operation to BOTH sides of the equation.',
    'Inverse operations on linear equations'),
  mcq('alg2', 'algebra', 'Systems of equations', 2, 'Solving 2×2 linear systems by substitution', 80,
    'If 2x + 3y = 12 and x − y = 1, what is x + y?',
    ['3', '4', '5', '7'], 2,
    'From the second equation x = y + 1. Substitute: 2(y+1) + 3y = 12 → 5y = 10 → y = 2, x = 3. So x + y = 5.',
    { 0: 'That is x alone; the question asks for x + y.', 1: 'Arithmetic slip when substituting (2·3 + 3·2 = 12 checks that x=3, y=2).' },
    'Add the equations after multiplying the second by 3: 2x+3y=12 and 3x−3y=3 sum to 5x = 15, x = 3.',
    'Solving for x and stopping — always re-read what was actually asked.',
    'Substitution / elimination'),
  mcq('alg3', 'algebra', 'Algebraic fractions', 2, 'Factoring to simplify rational expressions', 70,
    'Simplify (x² − 9) / (x − 3) for x ≠ 3.',
    ['x + 3', 'x − 3', 'x² + 3', '3 − x'], 0,
    'Factor the numerator as a difference of squares: (x−3)(x+3), then cancel (x−3), leaving x + 3.',
    { 1: 'Cancelling the wrong factor; (x−3) cancels, leaving (x+3).', 3: 'Sign error: the remaining factor is x + 3, not 3 − x.' },
    'Recognise a² − b² = (a−b)(a+b) instantly — no long division needed.',
    '"Cancelling" the x terms across addition/subtraction instead of factoring first.',
    'Difference of squares'),
  mcq('alg4', 'algebra', 'Absolute value', 3, 'Splitting absolute-value equations into cases', 90,
    'Solve |2x − 5| = 9.',
    ['x = 7 only', 'x = −2 only', 'x = 7 or x = −2', 'x = 2 or x = −7'], 2,
    '|A| = 9 means A = 9 or A = −9. Case 1: 2x−5 = 9 → x = 7. Case 2: 2x−5 = −9 → x = −2.',
    { 0: 'Only took the positive case; absolute values give TWO cases.', 1: 'Only took the negative case.' },
    'Write both cases immediately: 2x−5 = ±9, solve each.',
    'Dropping the negative case — |…| = positive number almost always has two solutions.',
    'Absolute-value case splitting'),
  mcq('alg5', 'algebra', 'Symmetric systems', 3, 'Using identities like difference of squares in systems', 110,
    'If x + y = 5 and x² − y² = 15, find xy.',
    ['3', '4', '5', '6'], 1,
    'x² − y² = (x+y)(x−y) = 15, and x+y = 5, so x−y = 3. Then x = (5+3)/2 = 4, y = 1, so xy = 4.',
    { 0: 'That is x − y, not xy.', 2: 'Re-used x + y = 5 instead of solving for the individual values.' },
    'From x+y=5 and x−y=3, halve-and-add: x = (5+3)/2 = 4, y = (5−3)/2 = 1.',
    'Not seeing the hidden factorisation (x+y)(x−y) and trying messy substitution.',
    'Difference of squares inside systems'),

  // ─── Functions ────────────────────────────────────────────
  mcq('fun1', 'functions', 'Evaluating functions', 1, 'Substituting inputs into functions', 40,
    'If f(x) = 2x + 3, what is f(4)?',
    ['9', '10', '11', '14'], 2,
    'Substitute: f(4) = 2(4) + 3 = 11.',
    { 0: 'Computed 2 + 3 + 4 by adding everything.', 1: 'Multiplied 2 × (4 + 3) = 14? No — multiplication binds first: 2·4 then + 3.' },
    'Replace every x with 4 in brackets: 2(4) + 3.',
    'Multiplying 2 × 4 + 3 in the wrong order (order of operations).',
    'Function notation'),
  mcq('fun2', 'functions', 'Composition', 2, 'Evaluating composite functions inside-out', 70,
    'If f(x) = x² + 1 and g(x) = 2x, what is f(g(3))?',
    ['13', '20', '35', '37'], 3,
    'Work inside-out: g(3) = 6, then f(6) = 6² + 1 = 37.',
    { 0: 'Treated f as 2x + 1 (mixed up the two function rules).', 1: 'Computed g(f(3)) = 2(10) = 20 — composition order reversed.', 2: 'Forgot the +1: got 36, then mis-keyed.' },
    'Always start from the innermost bracket and annotate: g(3)=6 → f(6)=37.',
    'Applying composition in the wrong order: f(g(x)) ≠ g(f(x)) in general.',
    'Composite functions'),
  mcq('fun3', 'functions', 'Domain', 2, 'Combining domain restrictions', 70,
    'What is the domain of f(x) = √(x − 2) + 1/(x − 5)?',
    ['All real numbers', 'x ≥ 2', 'x ≥ 2 and x ≠ 5', 'x > 5'], 2,
    'Two restrictions: the square root needs x − 2 ≥ 0 → x ≥ 2, and the fraction forbids x = 5. Both must hold.',
    { 0: 'Ignores both restrictions.', 1: 'Handles the root but forgets division by zero at x = 5.' },
    'Collect restrictions from EACH term, then intersect them.',
    'Handling one restriction and forgetting the other term.',
    'Domain of combined expressions'),
  mcq('fun4', 'functions', 'Inverse functions', 3, 'Algebraically finding inverses', 100,
    'Find the inverse of f(x) = (3x − 2)/5.',
    ['f⁻¹(x) = (5x + 2)/3', 'f⁻¹(x) = (5x − 2)/3', 'f⁻¹(x) = (3x + 2)/5', 'f⁻¹(x) = 3x + 2'], 0,
    'Write y = (3x−2)/5. Swap x and y: x = (3y−2)/5. Solve: 5x = 3y − 2 → y = (5x+2)/3.',
    { 1: 'Sign error moving the 2 across.', 2: 'Swapped coefficients but not the operations — check by composing: f⁻¹(f(0)) must equal 0.' },
    'Swap x/y first, THEN solve step by step — much less error-prone than doing algebra mentally.',
    '"Flipping the fraction" instead of properly swapping variables and solving.',
    'Inverse functions'),
  mcq('fun5', 'functions', 'Linear functions from points', 3, 'Building linear equations from two values', 90,
    'A linear function satisfies f(1) = 4 and f(3) = 10. What is f(5)?',
    ['14', '15', '16', '18'], 2,
    'Slope = (10 − 4)/(3 − 1) = 3, so f(x) = 3x + 1 (check: f(1) = 4 ✓). Then f(5) = 16.',
    { 1: 'Added slope repeatedly starting from the wrong base point.', 3: 'Used slope 2 from mis-pairing the points.' },
    'Since 5 is 2 steps past 3, add slope × 2: 10 + 3·2 = 16.',
    'Assuming equal x-steps mean equal f-steps without checking the slope first.',
    'Slope between points'),

  // ─── Probability ──────────────────────────────────────────
  mcq('pro1', 'probability', 'Counting outcomes', 1, 'Enumerating equally likely outcomes', 60,
    'A fair coin is tossed 3 times. What is the probability of exactly 2 heads?',
    ['1/8', '1/4', '3/8', '1/2'], 2,
    'There are 2³ = 8 equally likely sequences. Exactly two heads occurs in HHT, HTH, THH → 3 outcomes, so 3/8.',
    { 1: 'Counted only 2 favourable sequences; there are three places the single tail can sit.', 3: 'Confused "at least 2 heads" (which is 4/8) with "exactly 2 heads".' },
    'Favourable = C(3,2) = 3 positions for the tail; total = 8.',
    'Listing sequences incompletely (missing THH).',
    'Classical probability'),
  mcq('pro2', 'probability', 'Dependent events', 2, 'Multiplying probabilities without replacement', 80,
    'A bag has 4 red and 6 blue balls. Two balls are drawn WITHOUT replacement. What is P(both red)?',
    ['2/15', '4/25', '1/5', '2/9'], 0,
    'P(first red) = 4/10. Given that, P(second red) = 3/9. Multiply: (4/10)(3/9) = 12/90 = 2/15.',
    { 1: 'Used replacement probabilities (4/10 × 4/10).', 2: 'That is only the FIRST draw; the question asks about both.' },
    'Multiply 4/10 × 3/9 directly; simplify 12/90 by dividing by 6.',
    'Forgetting the denominator shrinks from 10 to 9 on the second draw.',
    'Conditional / dependent probability'),
  mcq('pro3', 'probability', 'Independence', 2, 'Applying the addition rule', 60,
    'Events A and B are independent with P(A) = 0.5 and P(B) = 0.4. What is P(A or B)?',
    ['0.6', '0.7', '0.9', '0.2'], 1,
    'Independent means P(A and B) = 0.5 × 0.4 = 0.2. Addition rule: 0.5 + 0.4 − 0.2 = 0.7.',
    { 0: 'Dropped a factor — likely used 0.5 + 0.4 − 0.3.', 2: 'Added the probabilities without subtracting the intersection (would exceed 1 for many pairs!).' },
    'P(A∪B) = P(A) + P(B) − P(A)P(B) for independent events, in one line.',
    'Adding probabilities of overlapping events without subtracting P(A∩B).',
    'Addition rule & independence'),
  mcq('pro4', 'probability', 'Conditional probability', 3, 'Computing conditional probabilities by counting', 130,
    'Two fair dice are rolled. What is P(sum is 8 | first die shows an even number)?',
    ['1/6', '1/4', '1/3', '5/36'], 0,
    'Given the first die is even, there are 18 equally likely outcomes. Sum 8 requires (2,6), (4,4), (6,2) → 3 outcomes. So 3/18 = 1/6.',
    { 1: 'Used 3 favourable over 12 — wrong conditioning space.', 2: 'Conditioned on the wrong event (all sums-8 pairs over something else).' },
    'Restrict the sample space to the condition FIRST (first die ∈ {2,4,6}: 18 outcomes), then count successes.',
    'Keeping all 36 outcomes instead of shrinking to the conditioned 18.',
    'Conditional probability'),
  mcq('pro5', 'probability', 'Complementary counting', 3, 'Using complements for "at least one"', 70,
    'A fair coin is tossed 4 times. What is the probability of AT LEAST one head?',
    ['15/16', '7/8', '11/16', '1/2'], 0,
    'P(no heads) = (1/2)⁴ = 1/16. So P(at least one) = 1 − 1/16 = 15/16.',
    { 1: 'Used only 3 tosses in the complement.', 3: 'That is the chance of heads on a single toss — not of at least one in four.' },
    '"At least one" → 1 − P(none). One calculation instead of four cases.',
    'Trying to add probabilities of 1, 2, 3, or 4 heads individually (error-prone).',
    'Complement rule'),
  mcq('pro6', 'probability', 'Complements with dice', 2, 'Spotting invalid probability shortcuts', 60,
    'A die is rolled twice. What is the probability of getting at least one six?',
    ['1/3', '11/36', '1/6', '25/36'], 1,
    'P(no six in one roll) = 5/6, so P(neither roll is a six) = 25/36. Complement: 1 − 25/36 = 11/36.',
    { 0: 'Added 1/6 + 1/6 — double-counts rolls where BOTH are sixes.', 3: 'That is P(NO six); the complement was forgotten.' },
    '1 − (5/6)² = 11/36 in one step.',
    'Adding P(A) + P(B) for overlapping events instead of using the complement.',
    'Complement rule'),

  // ─── Statistics ───────────────────────────────────────────
  num('sta1', 'statistics', 'Central tendency', 1, 'Computing the arithmetic mean', 45,
    'Compute the mean of the dataset: 4, 8, 9, 12, 7.', 8,
    'Sum = 4+8+9+12+7 = 40. Mean = 40 / 5 = 8.',
    'Pair numbers to sum quickly: (4+12)+(8+7)+9 = 16+15+9 = 40.',
    'Dividing by 4 (one less than the count) instead of 5.',
    'Mean'),
  mcq('sta2', 'statistics', 'Median', 2, 'Finding the median of an even-sized dataset', 60,
    'What is the median of: 10, 3, 7, 5, 14, 10?',
    ['7', '8.5', '9', '10'], 1,
    'Sort first: 3, 5, 7, 10, 10, 14. Even count → median is the average of the two middle values (7 + 10)/2 = 8.5.',
    { 0: 'Took the lower middle value instead of averaging the two middles.', 3: 'Picked a frequent-looking value — that confuses median with mode.' },
    'Cross out extremes pairwise: (3,14), (5,10), leaves 7 and 10 → average them.',
    'Taking the median BEFORE sorting the data.',
    'Median of even samples'),
  mcq('sta3', 'statistics', 'Robustness', 2, 'Choosing measures resistant to outliers', 50,
    'Which measure of central tendency is MOST affected by extreme outliers?',
    ['Median', 'Mode', 'Mean', 'Interquartile range'], 2,
    'The mean uses every value, so a single extreme outlier can drag it substantially. Median and IQR are position-based and robust.',
    { 0: 'The median is famously robust to outliers.', 2: 'Correct — but note the mode ignores magnitude entirely.' },
    'Remember: mean = sensitive, median = robust.',
    'Assuming all averages behave alike under skew.',
    'Outlier sensitivity'),
  mcq('sta4', 'statistics', 'Variance', 3, 'Computing population variance', 110,
    'What is the population variance of: 2, 4, 6, 8, 10?',
    ['6', '8', '10', '40'], 1,
    'Mean = 6. Squared deviations: 16, 4, 0, 4, 16 → sum 40. Variance = 40/5 = 8.',
    { 2: 'Close but arbitrary; recompute Σd² = 40 divided by n = 5.', 3: 'That is Σd² — variance divides by n.' },
    'Mean 6 sits at the centre; deviations are symmetric ±4, ±2, 0 → (16+4)·2/5 = 8.',
    'Reporting Σd² (or SD² of a SAMPLE with n−1) when the population variance is asked.',
    'Variance vs standard deviation'),
  mcq('sta5', 'statistics', 'Z-scores', 3, 'Standardising values', 80,
    'Exam scores follow a distribution with mean 75 and standard deviation 5. What is the z-score of a score of 85?',
    ['1', '1.5', '2', '2.5'], 2,
    'z = (x − μ)/σ = (85 − 75)/5 = 2.',
    { 0: 'Off by using σ = 10.', 1: 'Arithmetic slip: 10/5 is exactly 2.' },
    '(distance from mean) ÷ (standard deviation) — do the subtraction first.',
    'Dividing by the score instead of the standard deviation.',
    'Z-scores'),

  // ─── Linear algebra ───────────────────────────────────────
  mcq('lin1', 'linear', 'Dot products', 1, 'Computing dot products', 50,
    'Compute the dot product [1, 2, 3] · [4, −1, 2].',
    ['6', '8', '10', '12'], 1,
    '1·4 + 2·(−1) + 3·2 = 4 − 2 + 6 = 8.',
    { 0: 'Sign slip on the −1 term.', 2: 'Added instead of multiplied somewhere — recheck term by term.' },
    'Stack and multiply vertically: (4, −2, 6) then sum.',
    'Losing a minus sign on negative components.',
    'Dot product'),
  mcq('lin2', 'linear', 'Determinants (2×2)', 2, 'Evaluating 2×2 determinants', 50,
    'What is det([[3, 1], [4, 2]])?',
    ['2', '4', '6', '10'], 0,
    'det = ad − bc = 3·2 − 1·4 = 6 − 4 = 2.',
    { 1: 'Added diagonals instead of subtracting.', 2: 'Computed 3·4 − 1·2 with rows/columns swapped incorrectly.' },
    'ad − bc, read along the main diagonal first.',
    'Doing bc − ad (sign flip).',
    '2×2 determinant formula'),
  mcq('lin3', 'linear', 'Matrix multiplication', 2, 'Multiplying 2×2 matrices', 80,
    'Compute [[1, 2], [3, 4]] × [[0, 1], [1, 0]].',
    ['[[2, 1], [4, 3]]', '[[1, 2], [3, 4]]', '[[2, 4], [1, 3]]', '[[1, 0], [0, 1]]'], 0,
    'Row-by-column: top row = [1·0+2·1, 1·1+2·0] = [2, 1]; bottom row = [3·0+4·1, 3·1+4·0] = [4, 3].',
    { 1: 'That is the original matrix — multiplication changes entries here.', 2: 'Transposed layout — rows and columns were mixed.' },
    'Note the right matrix swaps columns, so the result is the left matrix with its columns swapped.',
    'Multiplying entry-wise instead of row-by-column.',
    'Matrix product'),
  mcq('lin4', 'linear', 'Determinants (3×3)', 3, 'Expanding 3×3 determinants', 120,
    'What is det([[2, 0, 1], [1, 3, 2], [1, 1, 1]])?',
    ['−2', '0', '1', '4'], 1,
    'Expand along the first row: 2·(3·1 − 2·1) − 0·(…) + 1·(1·1 − 3·1) = 2·1 + 1·(−2) = 0. The matrix is singular.',
    { 2: 'Sign slip in the cofactor expansion (the last minor is 1 − 3 = −2).', 3: 'Arithmetic error in the 2×2 minors.' },
    'The zero in position (1,2) kills one term — expand along row 1.',
    'Forgetting alternating signs (+ − +) in cofactor expansion.',
    'Cofactor expansion'),
  mcq('lin5', 'linear', 'Orthogonality', 3, 'Testing vectors for orthogonality', 90,
    'Which vector is orthogonal (perpendicular) to v = (2, 3, −6)?',
    ['(3, −2, 0)', '(1, 1, 1)', '(2, −3, 6)', '(6, 4, 0)'], 0,
    'Orthogonal ⟺ dot product = 0. Check (3, −2, 0): 2·3 + 3·(−2) + (−6)·0 = 6 − 6 + 0 = 0 ✓.',
    { 1: '(1,1,1)·v = 2 + 3 − 6 = −1 ≠ 0 — nearly, but not zero.', 2: 'That is a scaled reflection of v, parallel-ish not perpendicular: dot = 4 − 9 − 36 < 0.' },
    'You only need ONE quick dot product per option; kill negatives first.',
    'Judging perpendicularity visually instead of testing dot = 0.',
    'Orthogonality via dot product'),

  // ─── Calculus ─────────────────────────────────────────────
  mcq('cal1', 'calculus', 'Power rule', 1, 'Differentiating powers of x', 40,
    'What is d/dx (x³)?',
    ['3x²', 'x²', '3x³', 'x⁴/4'], 0,
    'Power rule: bring the exponent down and reduce it by 1 → 3x².',
    { 3: 'That is the INTEGRAL of x³ (antiderivative), not the derivative.' },
    'Power rule instantly: n = 3 → 3x².',
    'Integrating instead of differentiating.',
    'Power rule'),
  num('cal2', 'calculus', 'Definite integrals', 2, 'Evaluating simple definite integrals', 70,
    'Evaluate ∫₀² 2x dx.', 4,
    'Antiderivative of 2x is x². Evaluate: 2² − 0² = 4. (It is also the area of a triangle: ½·2·4.)',
    'Geometry shortcut: the region under 2x from 0 to 2 is a triangle with area ½·base·height.',
    'Plugging in only the upper limit and forgetting to subtract the lower evaluation.',
    'Fundamental theorem of calculus'),
  mcq('cal3', 'calculus', 'Product rule', 2, 'Applying the product rule', 70,
    'What is d/dx (x · eˣ)?',
    ['eˣ', 'x·eˣ', 'eˣ(x + 1)', 'eˣ(x − 1)'], 2,
    'Product rule: u′v + uv′ = 1·eˣ + x·eˣ = eˣ(1 + x).',
    { 1: 'Differentiated only the x factor.', 3: 'Sign error in the product rule.' },
    'u′v + uv′ with u = x, v = eˣ takes two seconds.',
    'Treating products like the chain rule (just differentiating one factor).',
    'Product rule'),
  mcq('cal4', 'calculus', 'Optimisation', 3, 'Classifying critical points with the second derivative', 120,
    'For f(x) = x³ − 3x, where does a LOCAL MAXIMUM occur?',
    ['x = −1', 'x = 1', 'x = ±1', 'No local maximum'], 0,
    'f′(x) = 3x² − 3 = 0 at x = ±1. Second derivative f″(x) = 6x: at x = −1, f″ = −6 < 0 → concave down → local maximum.',
    { 1: 'x = 1 has f″ = 6 > 0 — that is the local MINIMUM.', 2: 'Both are critical points but they classify differently; you must test each.' },
    'Factor f′ = 3(x−1)(x+1) to see roots fast, then sign-test around them.',
    'Stopping at f′(x) = 0 without classifying the critical points.',
    'First/second derivative tests'),
  mcq('cal5', 'calculus', 'Limits', 3, 'Evaluating trig limits', 70,
    'Evaluate lim(x→0) sin(3x) / x.',
    ['0', '1', '3', 'Does not exist'], 2,
    'Rewrite as 3 · sin(3x)/(3x). Since sin(u)/u → 1 as u → 0, the limit is 3·1 = 3.',
    { 1: 'Applied sin(u)/u → 1 but forgot the factor of 3 outside.' },
    'sin(kx)/x → k for any constant k.',
    'Quoting lim sin(x)/x = 1 without adjusting the inner argument.',
    'Standard trig limit'),

  // ─── Discrete mathematics ─────────────────────────────────
  mcq('dis1', 'discrete', 'Counting subsets', 1, 'Applying the power-set size formula', 40,
    'How many subsets does a set with 5 elements have (including the empty set)?',
    ['10', '25', '32', '120'], 2,
    'Each element is either in or out: 2⁵ = 32 subsets.',
    { 1: 'That would be 5² — subsets are 2 choices per element.', 3: 'That is 5! (permutations), unrelated to subsets.' },
    '2ⁿ, nothing more.',
    'Confusing subsets (2ⁿ) with permutations (n!).',
    'Power sets'),
  mcq('dis2', 'discrete', 'Combinations', 2, 'Computing combinations C(n, k)', 60,
    'In how many ways can a committee of 2 be chosen from 6 people?',
    ['12', '15', '30', '36'], 1,
    'Order does not matter: C(6,2) = (6·5)/2 = 15.',
    { 2: 'That is P(6,2) = 30 — ordered selections; a committee has no order.', 3: 'Double-counted pairs.' },
    'C(n,k) = n·(n−1)…/k! — for k = 2 just divide n(n−1) by 2.',
    'Using permutations where order should not matter.',
    'Combinations vs permutations'),
  num('dis3', 'discrete', 'Series', 2, 'Summing arithmetic series', 60,
    'Compute 1 + 2 + 3 + … + 100.', 5050,
    'Gauss pairing: (1+100) + (2+99) + … gives 50 pairs each summing to 101 → 50·101 = 5050. Formula: n(n+1)/2 = 100·101/2.',
    'n(n+1)/2 with n = 100 — instant.',
    'Answering 5000 from rounding 100·100/2.',
    'Arithmetic series formula'),
  mcq('dis4', 'discrete', 'Arrangement codes', 3, 'Counting sequences without repetition', 80,
    'A 3-digit code is formed from digits 1–5, using each digit at most once. How many codes are possible?',
    ['20', '60', '120', '125'], 1,
    'Sequential choices: 5 ways for digit 1, then 4, then 3 → 5·4·3 = 60.',
    { 3: 'That is 5³ — it allows repeated digits.', 2: 'That is 5! — too many for a 3-slot code.' },
    'Slots multiply: 5·4·3.',
    'Allowing repetition when "without repetition" is stated.',
    'Permutation counting'),
  mcq('dis5', 'discrete', 'Graphs', 3, 'Counting edges of complete graphs', 70,
    'How many edges does the complete graph K₄ (every pair of 4 vertices connected) have?',
    ['4', '5', '6', '8'], 2,
    'Every pair of vertices forms one edge: C(4,2) = 6.',
    { 0: 'That is the number of vertices, not edges.', 3: 'Over-counted pairs.' },
    'Kₙ has n(n−1)/2 edges: 4·3/2 = 6.',
    'Confusing vertices with edges.',
    'Complete graphs'),

  // ─── Logic & patterns ─────────────────────────────────────
  mcq('log1', 'logic', 'Number patterns', 1, 'Finding differences in sequences', 50,
    'What comes next: 2, 6, 12, 20, 30, …?',
    ['36', '40', '42', '44'], 2,
    'Differences grow: +4, +6, +8, +10 → next difference +12 → 30 + 12 = 42. (Pattern: n² + n.)',
    { 0: 'Assumed the differences stay at +6.', 1: 'Added +10 once more instead of the growing difference.' },
    'Take first differences; if they are not constant, take second differences.',
    'Assuming a constant difference without checking.',
    'Finite differences'),
  mcq('log2', 'logic', 'Syllogisms', 2, 'Drawing valid conclusions', 60,
    'All A are B. All B are C. Which conclusion MUST be true?',
    ['All A are C', 'All C are A', 'Some C are not A', 'No conclusion follows'], 0,
    'Chaining universal statements: every A is inside B, and every B is inside C, so every A is inside C.',
    { 1: 'Converse is not implied: C-elements outside A may exist.', 2: 'Nothing forces any C to lie outside A.' },
    'Draw nested circles (Euler diagram): A ⊂ B ⊂ C.',
    'Reversing implications ("all A are B" does not mean "all B are A").',
    'Categorical syllogisms'),
  mcq('log3', 'logic', 'Modus tollens', 2, 'Reasoning with contrapositives', 60,
    'Given: "If it rains, the match is cancelled." The match was NOT cancelled. What definitely follows?',
    ['It did not rain', 'It rained', 'The match would have been cancelled anyway', 'Nothing follows'], 0,
    'P → Q with ¬Q gives ¬P (modus tollens). If it had rained, the match WOULD have been cancelled; it was not, so it did not rain.',
    { 1: 'Contradicts the implication chain.', 3: 'Modus tollens IS valid — a definite conclusion exists.' },
    'Contrapositive thinking: ¬Q ⇒ ¬P.',
    'Affirming the consequent (inferring rain FROM cancellation) — that direction is invalid.',
    'Valid inference forms'),
  mcq('log4', 'logic', 'Logical equivalence', 3, 'Simplifying compound propositions', 100,
    'Which expression is logically equivalent to ¬A ∨ (A ∧ B)?',
    ['A → B', 'B → A', 'A ∨ B', '¬(A ∧ B)'], 0,
    'Distribute: ¬A ∨ (A∧B) = (¬A∨A) ∧ (¬A∨B) = True ∧ (¬A∨B) = ¬A∨B, which is exactly A → B.',
    { 2: 'Check A=true,B=false: original is false but A∨B is true — not equivalent.', 1: 'Test A=false,B=false: original is true, B→A is false.' },
    'Absorption law: X ∨ (X′ ∧ Y) = X ∨ Y with X = ¬A.',
    'Assuming OR and AND distribute like ordinary arithmetic.',
    'Propositional identities'),
  mcq('log5', 'logic', 'Doubling patterns', 3, 'Recognising exponential growth in sequences', 60,
    'What comes next: 2, 3, 5, 9, 17, …?',
    ['26', '31', '33', '34'], 2,
    'Differences double: +1, +2, +4, +8 → next +16 → 17 + 16 = 33. (Each term = previous×2 − 1.)',
    { 0: 'Assumed differences continue +9.', 1: 'Arithmetic slip: 17 + 16 = 33.' },
    'Second differences are geometric (doubling) → extrapolate the difference sequence.',
    'Testing only first differences and guessing linearly.',
    'Geometric difference patterns'),

  // ─── Quantitative reasoning ───────────────────────────────
  mcq('qnt1', 'quant', 'Percentages', 1, 'Computing percentages of quantities', 45,
    'What is 15% of 240?',
    ['24', '32', '36', '42'], 2,
    '10% of 240 = 24; 5% = 12; together 36.',
    { 0: 'That is 10%, not 15%.', 1: 'Mis-scaled the percentage.' },
    '10% + half-of-10% mental math.',
    'Slipping a decimal place (240 × 0.015 = 3.6).',
    'Percentage decomposition'),
  mcq('qnt2', 'quant', 'Average rates', 2, 'Computing overall averages correctly', 90,
    'A car travels 150 km in 1.5 h, then 100 km in 2 h. What is its average speed for the whole trip?',
    ['65 km/h', '≈ 71.4 km/h', '75 km/h', '80 km/h'], 1,
    'Average speed = TOTAL distance / TOTAL time = (150 + 100) / (1.5 + 2) = 250 / 3.5 ≈ 71.4 km/h.',
    { 2: 'That is the average of the two speeds ((100+50)/2 style error is different) — actually averaging 100 km/h and 50 km/h gives 75, which is wrong because times differ.', 3: 'Too high — check total distance ÷ total time again.' },
    'Never average speeds directly; always total distance ÷ total time.',
    'Averaging the two segment speeds instead of weighting by time.',
    'Weighted averages'),
  mcq('qnt3', 'quant', 'Work rates', 2, 'Combining work rates', 80,
    'Worker A completes a job in 6 hours, worker B in 3 hours. Working together, how long?',
    ['2 hours', '3 hours', '4.5 hours', '9 hours'], 0,
    'Rates add: 1/6 + 1/3 = 1/2 job per hour → 2 hours per job.',
    { 1: 'That is B alone.', 2: 'Averaged the two times instead of adding rates.' },
    'Harmonic intuition: reciprocal-sum 1/(1/6+1/3) = 2.',
    'Averaging completion times (4.5 h) instead of adding rates.',
    'Rate problems'),
  mcq('qnt4', 'quant', 'Successive change', 3, 'Compounding percentage changes', 70,
    'A price rises by 20%, then falls by 20%. What is the NET change?',
    ['No net change', '4% decrease', '2% increase', '4% increase'], 1,
    'Multiply factors: 1.20 × 0.80 = 0.96 → a 4% decrease overall.',
    { 0: 'Percentages act on DIFFERENT bases, so they do not cancel.' },
    'Multiply growth factors; never add/subtract successive percentages.',
    'Assuming +20% and −20% cancel out.',
    'Compound percentage change'),
  mcq('qnt5', 'quant', 'Age word problems', 3, 'Setting up equations from age relations', 100,
    'Tom is twice as old as Ann. In 6 years, the sum of their ages will be 54. How old is Tom NOW?',
    ['21', '24', '28', '32'], 2,
    'Let Ann = a, Tom = 2a. In 6 years: (2a+6) + (a+6) = 54 → 3a = 42 → a = 14. Tom now = 28.',
    { 1: 'Solved for Ann and reported her age doubled incorrectly.', 2: 'Correct — verify: 28 + 14 = 42 now; in 6 years 34 + 20 = 54 ✓.' },
    'Both ages gain exactly 6, so future sum = current sum + 12 → current sum 42, split 2:1 → 28/14.',
    'Forgetting that BOTH ages increase by 6.',
    'Linear modelling'),

  // ─── Programming fundamentals ─────────────────────────────
  mcq('prg1', 'programming', 'Loops & ranges', 1, 'Tracing simple loops', 45,
    'What does this Python code print?\nfor i in range(3):\n    print(i)',
    ['1 2 3', '0 1 2', '0 1 2 3', '1 2'], 1,
    'range(3) yields 0, 1, 2 — it stops BEFORE 3 and starts at 0 by default.',
    { 0: 'range starts at 0, not 1.', 2: 'range excludes the endpoint.' },
    'range(n) = {0, 1, …, n−1} — memorise it once.',
    'Thinking range includes its endpoint.',
    'Zero-based iteration'),
  mcq('prg2', 'programming', 'Loop accumulation', 2, 'Tracing accumulators through loops', 75,
    'What is the value of s after:\ns = 0\nfor i in [2, 4, 6]:\n    s = s + i * i',
    ['24', '36', '54', '56'], 3,
    'Accumulate squares: 4 + 16 + 36 = 56.',
    { 0: 'That is the plain sum 2+4+6 without squaring.', 1: 'Squared only the last element.' },
    'Track s in a tiny table: 0→4→20→56.',
    'Operator precedence: i * i is computed fully before adding to s.',
    'Accumulator pattern'),
  mcq('prg3', 'programming', 'Recursion', 2, 'Tracing recursive calls', 85,
    'def f(n):\n    if n <= 1:\n        return 1\n    return n * f(n - 1)\n\nWhat is f(4)?',
    ['10', '24', '64', '120'], 1,
    'This computes the factorial: 4·f(3) = 4·3·f(2) = 4·3·2·f(1) = 4·3·2·1 = 24.',
    { 0: 'Added instead of multiplied (triangular number pattern).', 3: 'That is f(5) — off by one level of recursion.' },
    'Unwind the stack bottom-up: f(1)=1 → f(2)=2 → f(3)=6 → f(4)=24.',
    'Base-case off-by-one (if it returned 0, EVERYTHING would be 0).',
    'Recursion & base cases'),
  mcq('prg4', 'programming', 'Nested loops', 3, 'Counting nested-loop iterations', 90,
    'How many lines does this print?\nfor i in range(1, 4):\n    for j in range(i, 4):\n        print(i, j)',
    ['5', '6', '9', '12'], 1,
    'Iterations depend on i: i=1 → j∈{1,2,3} (3), i=2 → 2, i=3 → 1. Total 3+2+1 = 6.',
    { 2: 'That assumes the inner loop ALWAYS runs 3 times; it shrinks with i.', 3: 'Same dependency mistake with larger counts.' },
    'Sum the inner counts per outer value — triangular numbers again.',
    'Multiplying loop bounds blindly when the inner bound depends on the outer variable.',
    'Dependent nested loops'),
  mcq('prg5', 'programming', 'Default arguments', 3, 'Understanding mutable default pitfalls', 100,
    'def add(item, box=[]):\n    box.append(item)\n    return box\n\nAfter calling add(1) then add(2), what does the SECOND call return?',
    ['[2]', '[1, 2]', '[1]', 'It raises an error'], 1,
    'The default list is created ONCE at definition time and shared across calls, so both appends land in the same list: [1, 2].',
    { 0: 'The default object persists between calls — earlier items remain.', 2: 'Same shared-list reasoning: item 1 is still in there.' },
    'Golden rule: never use mutable defaults; use None and create inside.',
    'Assuming defaults are re-evaluated on every call.',
    'Shared mutable state'),

  // ─── Algorithms & data structures ─────────────────────────
  mcq('algo1', 'algo', 'Stacks', 1, 'Matching structures to use-cases', 45,
    'Which data structure is the natural fit for an UNDO feature in an editor?',
    ['Queue', 'Stack', 'Binary tree', 'Hash table'], 1,
    'Undo reverses the most recent action first — Last In, First Out = a stack.',
    { 0: 'Queues are First-In-First-Out — wrong order for undo.' },
    'Match keywords: undo/backtracking → stack; waiting lines/printers → queue.',
    'Mixing up LIFO and FIFO semantics.',
    'LIFO vs FIFO'),
  mcq('algo2', 'algo', 'Binary search', 2, 'Analysing logarithmic search', 70,
    'Using binary search on a SORTED list of 1000 items, roughly how many comparisons in the worst case?',
    ['5', '10', '100', '512'], 1,
    'Each comparison halves the range: 2¹⁰ = 1024 ≥ 1000, so about ⌈log₂(1000)⌉ ≈ 10.',
    { 0: 'Halving 1000 five times still leaves ~31 items.', 2: 'Linear-search territory — far more than needed.' },
    '2^k ≥ n → smallest k. 2¹⁰ = 1024 covers 1000.',
    'Confusing O(log n) with n/2-style counts.',
    'Logarithmic complexity'),
  mcq('algo3', 'algo', 'Array indexing', 2, 'Knowing costs of basic operations', 50,
    'What is the time complexity of accessing an array element BY INDEX?',
    ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 0,
    'Arrays store elements contiguously; index i maps straight to a memory address — constant time.',
    { 2: 'O(n) applies to SEARCHING an unsorted array, not indexed access.' },
    'Direct addressing = constant time.',
    'Conflating access-by-index with search.',
    'Complexity of array ops'),
  mcq('algo4', 'algo', 'Hash-based techniques', 3, 'Choosing optimal algorithms', 110,
    'Given an unsorted array, what is the best AVERAGE-CASE approach to find whether two elements sum to a target?',
    ['Sort, then scan with two pointers — O(n log n)', 'Check every pair — O(n²)', 'Store seen values in a hash set while scanning — O(n)', 'Build a balanced BST — O(n log n)'], 2,
    'One pass with a hash set: for each x check if target − x was already seen. O(n) time, O(n) extra space — beats sorting-based O(n log n).',
    { 0: 'Correct complexity-wise but not OPTIMAL — hashing avoids the sort entirely.', 1: 'Brute force; quadratic blow-up on large arrays.' },
    'Trade memory for speed: hash lookup turns the inner scan into O(1).',
    'Defaulting to sort-first strategies when a hash set gives linear time.',
    'Hash sets for complement lookups'),
  mcq('algo5', 'algo', 'Graph traversal', 3, 'Selecting traversal algorithms', 80,
    'Which traversal finds SHORTEST paths in an UNWEIGHTED graph?',
    ['Depth-first search', 'Breadth-first search', 'Pre-order traversal', 'Random walk'], 1,
    'BFS explores nodes layer by layer, so the first time it reaches a node it has used the fewest edges possible.',
    { 0: 'DFS dives deep and can reach nodes via longer paths first.' },
    'Unweighted shortest path = BFS. Weighted → Dijkstra.',
    'Using DFS and assuming discovery order equals shortest distance.',
    'BFS layer property'),

  // ─── CS fundamentals ──────────────────────────────────────
  mcq('csf1', 'csf', 'Number systems', 1, 'Converting binary to decimal', 50,
    'What is the decimal value of the binary number 1011?',
    ['9', '11', '13', '15'], 1,
    'Bits: 8 + 0 + 2 + 1 = 11.',
    { 0: 'Missed the 2¹ bit.', 3: 'That is 1111 — all ones.' },
    'Weights 8-4-2-1: add weights under each 1.',
    'Reading bits right-to-left with descending place values.',
    'Positional notation'),
  mcq('csf2', 'csf', 'Memory types', 2, 'Classifying storage volatility', 50,
    'Which of these is VOLATILE memory (loses contents when power is off)?',
    ['SSD', 'RAM', 'HDD', 'DVD'], 1,
    'RAM is working memory: fast but erased on power loss. SSD/HDD/DVD retain data persistently.',
    { 0: 'SSDs are non-volatile flash storage.' },
    'Volatile = needs continuous power = RAM (and CPU caches).',
    'Calling all memory "storage".',
    'Volatile vs persistent memory'),
  mcq('csf3', 'csf', 'CPU cache', 2, 'Explaining hardware roles', 60,
    'What best describes what a CPU CACHE does?',
    ['Permanent storage for user files', 'Small, very fast memory near the CPU holding frequently used data', 'Memory reserved exclusively for the GPU', 'An automatic backup of the hard drive'], 1,
    'Caches bridge the huge speed gap between CPU registers and main memory by keeping hot data close to the processor.',
    { 0: 'Files live on disk; caches are transient.' },
    'Cache = speed optimisation, transparent to programs.',
    'Describing RAM or disk when asked about cache.',
    'Memory hierarchy'),
  mcq('csf4', 'csf', 'Networking basics', 3, 'Recalling protocol fundamentals', 50,
    'How many bits are in an IPv4 address?',
    ['16 bits', '32 bits', '64 bits', '128 bits'], 1,
    'IPv4 addresses are 32-bit numbers (four 8-bit octets, e.g., 192.168.0.1).',
    { 3: '128 bits describes IPv6.' },
    'Four octets × 8 bits = 32.',
    'Mixing up IPv4 with IPv6 sizes.',
    'IPv4 addressing'),
  mcq('csf5', 'csf', 'Compilers vs interpreters', 3, 'Distinguishing translation strategies', 70,
    'Which statement about compilers and interpreters is TRUE?',
    ['A compiler translates the whole program before execution; an interpreter executes source line by line', 'An interpreter translates the whole program to machine code first', 'Compilers run programs line by line at runtime', 'They are two names for the same thing'], 0,
    'Compilers translate ahead of time to machine code; interpreters read and execute source incrementally.',
    { 1: 'That is compilation behaviour attributed to the wrong tool.' },
    'Ahead-of-time = compiler; on-the-fly = interpreter.',
    'Swapping the definitions of the two tools.',
    'Program translation'),

  // ─── Data interpretation & AI reasoning ───────────────────
  mcq('dat1', 'dat', 'Percentage change', 1, 'Interpreting changes between figures', 50,
    'Sales grew from 120 units (2021) to 150 units (2022). What was the percentage increase?',
    ['20%', '25%', '30%', '50%'], 1,
    'Increase = 30 units on a base of 120 → 30/120 = 25%.',
    { 0: 'Divided by the NEW value (30/150) — percentage change uses the ORIGINAL base.', 3: 'Compared absolute gap to the wrong scale.' },
    'change ÷ original, always.',
    'Using the new value as the denominator.',
    'Percentage change bases'),
  mcq('dat2', 'dat', 'Table shares', 2, 'Combining categories from tables', 70,
    'Department headcount: A = 40, B = 25, C = 20, D = 15 (total 100). What share do B and C hold TOGETHER?',
    ['35%', '40%', '45%', '55%'], 2,
    'B + C = 45 of 100 total → 45%.',
    { 0: 'Only counted B plus part of C.', 3: 'That is everyone except A minus D territory — recompute 25 + 20.' },
    'Total is conveniently 100, so counts ARE percentages.',
    'Re-dividing by the wrong total when the total is not 100.',
    'Part-to-whole ratios'),
  mcq('dat3', 'dat', 'Supervised learning', 2, 'Identifying learning paradigms', 70,
    'Which task is SUPERVISED learning?',
    ['Grouping customers into clusters without labels', 'Predicting email spam using messages labelled spam/not-spam', 'Discovering patterns in raw clickstreams', 'Trial-and-error play with rewards'], 1,
    'Supervised learning learns a mapping from inputs to KNOWN labels — a labelled spam corpus is the textbook example.',
    { 0: 'Clustering without labels is unsupervised.', 3: 'Reward-driven trial and error is reinforcement learning.' },
    'Labels present? supervised. No labels, structure-finding? unsupervised. Rewards? RL.',
    'Calling clustering "supervised" because a human reviews results afterwards.',
    'ML paradigms'),
  mcq('dat4', 'dat', 'Model diagnostics', 3, 'Diagnosing model behaviour', 80,
    'A model scores 99% accuracy on TRAINING data but only 62% on NEW test data. What is this called?',
    ['Underfitting', 'Overfitting', 'High bias', 'Vanishing gradient'], 1,
    'Memorising training data while failing to generalise is the definition of overfitting (low training error, high test error).',
    { 0: 'Underfitting performs POORLY everywhere.', 2: 'High bias ≈ underfitting — also inconsistent with the 99% training score.' },
    'Big train/test gap → overfit; uniformly poor → underfit.',
    'Blaming the test set instead of diagnosing generalisation failure.',
    'Bias-variance tradeoff'),
  mcq('dat5', 'dat', 'Skewed distributions', 3, 'Choosing statistics for skewed data', 70,
    'A company has a few extremely high executive salaries and many modest ones. Which statistic BEST represents the typical salary?',
    ['Mean', 'Median', 'Range', 'Standard deviation'], 1,
    'Strong right-skew drags the mean upward; the median (middle value) stays representative of the typical employee.',
    { 0: 'The outliers inflate the mean well above typical salaries.' },
    'Skewed data → report the median.',
    'Defaulting to the mean for "average" regardless of distribution shape.',
    'Robust statistics'),
];

// Diagnostic: easiest + hardest available question per topic, interleaved so
// consecutive questions rarely share a topic (matches mixed-format screening).
export function diagnosticBlueprint() {
  const picks = [];
  for (const t of TOPICS) {
    const qs = QUESTIONS.filter((q) => q.topic === t.id);
    qs.sort((a, b) => a.diff - b.diff);
    picks.push(qs[0], qs[qs.length - 1]);
  }
  const inter = [];
  const half = Math.ceil(picks.length / 2);
  for (let i = 0; i < half; i++) {
    if (picks[i]) inter.push(picks[i]);
    if (picks[half + i]) inter.push(picks[half + i]);
  }
  return inter;
}

export const MOCK_CONFIG = { count: 30, minutes: 45 };
export const DIAGNOSTIC_CONFIG = { minutes: 40, secondsPerQuestion: 90 };

// Official-topic mix for mock exams: Math-heavy, mirroring the public syllabus emphasis.
const MOCK_MIX = [
  'algebra', 'functions', 'probability', 'statistics', 'linear', 'calculus',
  'discrete', 'logic', 'quant', 'programming', 'algo', 'csf', 'dat',
];

export function mockBlueprint(rand = Math.random) {
  const pool = [...QUESTIONS].sort(() => rand() - 0.5);
  const picked = [];
  const usedByTopic = new Map();
  // Round-robin across topics so mocks mirror the published topic spread.
  for (let round = 0; round < 3 && picked.length < MOCK_CONFIG.count; round++) {
    for (const topic of MOCK_MIX.sort(() => rand() - 0.5)) {
      if (picked.length >= MOCK_CONFIG.count) break;
      const used = usedByTopic.get(topic) || new Set();
      const q = pool.find((c) => c.topic === topic && !used.has(c.id) && !picked.some((p) => p.id === c.id));
      if (q) { picked.push(q); used.add(q.id); usedByTopic.set(topic, used); }
    }
  }
  return picked.sort(() => rand() - 0.5);
}
